In [2]:
# Designing a Data-Driven Same-Day Delivery Rollout Strategy

## A Product Management & Supply Chain Analytics Case Study

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 1000)

In [4]:
df = pd.read_csv("data/raw/DataCoSupplyChainDataset.csv", encoding="latin1")

In [5]:
df.head()

       Type  Days for shipping (real)  Days for shipment (scheduled)  Benefit per order  Sales per customer   Delivery Status  Late_delivery_risk  Category Id   Category Name Customer City Customer Country Customer Email Customer Fname  Customer Id Customer Lname Customer Password Customer Segment Customer State           Customer Street  Customer Zipcode  Department Id Department Name   Latitude   Longitude        Market  Order City Order Country  Order Customer Id order date (DateOrders)  Order Id  Order Item Cardprod Id  Order Item Discount  Order Item Discount Rate  Order Item Id  Order Item Product Price  Order Item Profit Ratio  Order Item Quantity   Sales  Order Item Total  Order Profit Per Order    Order Region      Order State     Order Status  Order Zipcode  Product Card Id  Product Category Id  Product Description                                 Product Image  Product Name  Product Price  Product Status shipping date (DateOrders)   Shipping Mode
0     DEBIT                         3                              4          91.250000          314.640015  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Cally        20755       Holloway         XXXXXXXXX         Consumer             PR  5365 Noble Nectar Island             725.0              2         Fitness  18.251453  -66.037056  Pacific Asia      Bekasi     Indonesia              20755         1/31/2018 22:56     77202                    1360            13.110000                      0.04         180517                    327.75                     0.29                    1  327.75        314.640015               91.250000  Southeast Asia  Java Occidental         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0             2/3/2018 22:56  Standard Class
1  TRANSFER                         5                              4        -249.089996          311.359985     Late delivery                   1           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX          Irene        19492           Luna         XXXXXXXXX         Consumer             PR          2679 Rustic Loop             725.0              2         Fitness  18.279451  -66.037064  Pacific Asia     Bikaner         India              19492         1/13/2018 12:27     75939                    1360            16.389999                      0.05         179254                    327.75                    -0.80                    1  327.75        311.359985             -249.089996      South Asia         Rajastán          PENDING            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/18/2018 12:27  Standard Class
2      CASH                         4                              4        -247.779999          309.720001  Shipping on time                   0           73  Sporting Goods      San Jose          EE. UU.      XXXXXXXXX        Gillian        19491      Maldonado         XXXXXXXXX         Consumer             CA      8510 Round Bear Gate           95125.0              2         Fitness  37.292233 -121.881279  Pacific Asia     Bikaner         India              19491         1/13/2018 12:06     75938                    1360            18.030001                      0.06         179253                    327.75                    -0.80                    1  327.75        309.720001             -247.779999      South Asia         Rajastán           CLOSED            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/17/2018 12:06  Standard Class
3     DEBIT                         3                              4          22.860001          304.809998  Advance shipping                   0           73  Sporting Goods   Los Angeles          EE. UU.      XXXXXXXXX           Tana        19490           Tate         XXXXXXXXX      Home Office             CA           3200 Amber Bend           90027.0              2         Fitness  34.125946 -118.291016  Pacific Asia  Townsville     Australia              19490         1/13/2018 11:45     75937                    1360            22.940001                      0.07         179252                    327.75                     0.08                    1  327.75        304.809998               22.860001         Oceania       Queensland         COMPLETE            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/16/2018 11:45  Standard Class
4   PAYMENT                         2                              4         134.210007          298.250000  Advance shipping                   0           73  Sporting Goods        Caguas      Puerto Rico      XXXXXXXXX           Orli        19489      Hendricks         XXXXXXXXX        Corporate             PR  8671 Iron Anchor Corners             725.0              2         Fitness  18.253769  -66.037048  Pacific Asia  Townsville     Australia              19489         1/13/2018 11:24     75936                    1360            29.500000                      0.09         179251                    327.75                     0.45                    1  327.75        298.250000              134.210007         Oceania       Queensland  PENDING_PAYMENT            NaN             1360                   73                  NaN  http://images.acmesports.sports/Smart+watch   Smart watch          327.75               0            1/15/2018 11:24  Standard Class

In [6]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [7]:
df.shape

(180519, 53)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [9]:
df.head().T

                                                                          0                                             1                                             2                                             3                                             4
Type                                                                  DEBIT                                      TRANSFER                                          CASH                                         DEBIT                                       PAYMENT
Days for shipping (real)                                                  3                                             5                                             4                                             3                                             2
Days for shipment (scheduled)                                             4                                             4                                             4                                             4                                             4
Benefit per order                                                     91.25                                   -249.089996                                   -247.779999                                     22.860001                                    134.210007
Sales per customer                                               314.640015                                    311.359985                                    309.720001                                    304.809998                                        298.25
Delivery Status                                            Advance shipping                                 Late delivery                              Shipping on time                              Advance shipping                              Advance shipping
Late_delivery_risk                                                        0                                             1                                             0                                             0                                             0
Category Id                                                              73                                            73                                            73                                            73                                            73
Category Name                                                Sporting Goods                                Sporting Goods                                Sporting Goods                                Sporting Goods                                Sporting Goods
Customer City                                                        Caguas                                        Caguas                                      San Jose                                   Los Angeles                                        Caguas
Customer Country                                                Puerto Rico                                   Puerto Rico                                       EE. UU.                                       EE. UU.                                   Puerto Rico
Customer Email                                                    XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX
Customer Fname                                                        Cally                                         Irene                                       Gillian                                          Tana                                          Orli
Customer Id                                                           20755                                         19492                                         19491                                         19490                                         19489
Customer Lname                                                     Holloway                                          Luna                                     Maldonado                                          Tate                                     Hendricks
Customer Password                                                 XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX                                     XXXXXXXXX
Customer Segment                                                   Consumer                                      Consumer                                      Consumer                                   Home Office                                     Corporate
Customer State                                                           PR                                            PR                                            CA                                            CA                                            PR
Customer Street                                    5365 Noble Nectar Island                              2679 Rustic Loop                          8510 Round Bear Gate                               3200 Amber Bend                      8671 Iron Anchor Corners
Customer Zipcode                                                      725.0                                         725.0                                       95125.0                                       90027.0                                         725.0
Department Id                                                             2                                             2                                             2                                             2                                             2
Department Name                                                     Fitness                                       Fitness                                       Fitness                                       Fitness                                       Fitness
Latitude                                                          18.251453                                     18.279451                                     37.292233                                     34.125946                                     18.253769
Longitude                                                        -66.037056                                    -66.037064                                   -121.881279                                   -118.291016                                    -66.037048
Market                                                         Pacific Asia                                  Pacific Asia                                  Pacific Asia                                  Pacific Asia                                  Pacific Asia
Order City                                                           Bekasi                                       Bikaner                                       Bikaner                                    Townsville                                    Townsville
Order Country                                                     Indonesia                                         India                                         India                                     Australia                                     Australia
Order Customer Id                                                     20755                                         19492                                         19491                                         19490                                         19489
order date (DateOrders)                                     1/31/2018 22:56                               1/13/2018 12:27                               1/13/2018 12:06                               1/13/2018 11:45                               1/13/2018 11:24
Order Id                                                              77202                                         75939                                         75938                                         75937                                         75936
Order Item Cardprod Id                                                 1360                                          1360                                          1360                                          1360                                          1360
Order Item Discount                                                   13.11                                     16.389999                                     18.030001                                     22.940001                                          29.5
Order Item Discount Rate                                               0.04                                          0.05                                          0.06                                          0.07                                          0.09
Order Item Id                                                        180517                                        179254                                        179253                                        179252                                        179251
Order Item Product Price                                             327.75                                        327.75                                        327.75                                        327.75                                        327.75
Order Item Profit Ratio                                                0.29                                          -0.8                                          -0.8                                          0.08                                          0.45
Order Item Quantity                                                       1                                             1                                             1                                             1                                             1
Sales                                                                327.75                                        327.75                                        327.75                                        327.75                                        327.75
Order Item Total                                                 314.640015                                    311.359985                                    309.720001                                    304.809998                                        298.25
Order Profit Per Order                                                91.25                                   -249.089996                                   -247.779999                                     22.860001                                    134.210007
Order Region                                                 Southeast Asia                                    South Asia                                    South Asia                                       Oceania                                       Oceania
Order State                                                 Java Occidental                                      Rajastán                                      Rajastán                                    Queensland                                    Queensland
Order Status                                                       COMPLETE                                       PENDING                                        CLOSED                                      COMPLETE                               PENDING_PAYMENT
Order Zipcode                                                           NaN                                           NaN                                           NaN                                           NaN                                           NaN
Product Card Id                                                        1360                                          1360                                          1360                                          1360                                          1360
Product Category Id                                                      73                                            73                                            73                                            73                                            73
Product Description                                                     NaN                                           NaN                                           NaN                                           NaN                                           NaN
Product Image                  http://images.acmesports.sports/Smart+watch   http://images.acmesports.sports/Smart+watch   http://images.acmesports.sports/Smart+watch   http://images.acmesports.sports/Smart+watch   http://images.acmesports.sports/Smart+watch
Product Name                                                   Smart watch                                   Smart watch                                   Smart watch                                   Smart watch                                   Smart watch
Product Price                                                        327.75                                        327.75                                        327.75                                        327.75                                        327.75
Product Status                                                            0                                             0                                             0                                             0                                             0
shipping date (DateOrders)                                   2/3/2018 22:56                               1/18/2018 12:27                               1/17/2018 12:06                               1/16/2018 11:45                               1/15/2018 11:24
Shipping Mode                                                Standard Class                                Standard Class                                Standard Class                                Standard Class                                Standard Class

In [10]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Order Id                              0
Order Country                         0
Order Customer Id                     0
Customer Fname                        0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Id                           0
Days for shipping (real)              0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Shipping Mode                         0
dtype: int64

In [11]:
df["Order Id"].nunique()

65752

In [12]:
df["Order Item Id"].nunique()

180519

In [13]:
df["Customer Id"].nunique()

20652

In [14]:
df["Product Name"].nunique()

118

# Business Data Dictionary

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.nunique().sort_values()

Product Description                   0
Product Status                        1
Customer Password                     1
Customer Email                        1
Late_delivery_risk                    2
Customer Country                      2
Customer Segment                      3
Type                                  4
Shipping Mode                         4
Delivery Status                       4
Days for shipment (scheduled)         4
Order Item Quantity                   5
Market                                5
Days for shipping (real)              7
Order Status                          9
Department Id                        11
Department Name                      11
Order Item Discount Rate             18
Order Region                         23
Customer State                       46
Category Name                        50
Category Id                          51
Product Category Id                  51
Product Price                        75
Order Item Product Price             75
Order Item Cardprod Id              118
Product Name                        118
Product Image                       118
Product Card Id                     118
Order Item Profit Ratio             162
Order Country                       164
Sales                               193
Customer City                       563
Order Zipcode                       609
Customer Fname                      782
Customer Zipcode                    995
Order Item Discount                1017
Order State                        1089
Customer Lname                     1109
Order Item Total                   2927
Sales per customer                 2927
Order City                         3597
Longitude                          4487
Customer Street                    7458
Latitude                          11250
Order Customer Id                 20652
Customer Id                       20652
Order Profit Per Order            21998
Benefit per order                 21998
shipping date (DateOrders)        63701
Order Id                          65752
order date (DateOrders)           65752
Order Item Id                    180519
dtype: int64

In [18]:
df.select_dtypes(include="object").columns

/var/folders/ym/c3752zmj1xqcmq09s55tpl180000gn/T/ipykernel_83251/1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['Type', 'Delivery Status', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Department Name', 'Market', 'Order City', 'Order Country', 'order date (DateOrders)', 'Order Region', 'Order State', 'Order Status', 'Product Image', 'Product Name', 'shipping date (DateOrders)', 'Shipping Mode'], dtype='str')

In [19]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(df[col].value_counts().head())

/var/folders/ym/c3752zmj1xqcmq09s55tpl180000gn/T/ipykernel_83251/123410762.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

Type
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

Delivery Status
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Category Name
Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Name: count, dtype: int64

Customer City
Customer City
Caguas         66770
Chicago         3885
Los Angeles     3417
Brooklyn        3412
New York        1816
Name: count, dtype: int64

Customer Country
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

Customer Email
Customer Email
XXXXXXXXX    180519
Name: count, dtype: int64

Customer Fname
Customer Fname
Mary       65150
James       1835
Robert      1759
Michael     1680
David       1625
Name: count, dtype: int64

Customer Lname
Customer Lname
Smith       64104
Johnson       989
Brown         909
Williams      869
Jones         859
Name: count, dtype: int64

Customer Password
Customer Password
XXXXXXXXX    180519
Name: count, dtype: int64

Customer Segment
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

Customer State
Customer State
PR    69373
CA    29223
NY    11327
TX     9103
IL     7631
Name: count, dtype: int64

Customer Street
Customer Street
9126 Wishing Expressway     122
4388 Burning Goose Ridge    117
4720 Noble Hills Wynd       116
2878 Hazy Wagon  Thicket    113
398 Emerald Grove           109
Name: count, dtype: int64

Department Name
Department Name
Fan Shop    66861
Apparel     48998
Golf        33220
Footwear    14525
Outdoors     9686
Name: count, dtype: int64

Market
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

Order City
Order City
Santo Domingo    2211
New York City    2202
Los Angeles      1845
Tegucigalpa      1783
Managua          1682
Name: count, dtype: int64

Order Country
Order Country
Estados Unidos    24840
Francia           13222
México            13172
Alemania           9564
Australia          8497
Name: count, dtype: int64

order date (DateOrders)
order date (DateOrders)
10/25/2016 14:39    5
3/30/2016 4:37      5
11/28/2016 1:18     5
9/8/2015 12:15      5
8/4/2017 2:31       5
Name: count, dtype: int64

Order Region
Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Name: count, dtype: int64

Order State
Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
Name: count, dtype: int64

Order Status
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
Name: count, dtype: int64

Product Image
Product Image
http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck               24515
http://images.acmesports.sports/Nike+Men%27s+CJ+Elite+2+TD+Football+Cleat      22246
http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo         21035
http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest           19298
http://images.acmesports.sports/Field+%26+Stream+Sportsman+16+Gun+Fire+Safe    17325
Name: count, dtype: int64

Product Name
Product Name
Perfect Fitness Perfect Rip Deck             24515
Nike Men's CJ Elite 2 TD Football Cleat      22246
Nike Men's Dri-FIT Victory Golf Polo         21035
O'Brien Men's Neoprene Life Vest             19298
Field & Stream Sportsman 16 Gun Fire Safe    17325
Name: count, dtype: int64

shipping date (DateOrders)
shipping date (DateOrders)
5/9/2015 18:02      10
9/27/2015 20:28     10
9/24/2015 23:48     10
8/1/2015 18:37      10
11/15/2016 13:45    10
Name: count, dtype: int64

Shipping Mode
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64